apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: sops-akv-decryptor
  namespace: flux-system
spec:
  clientID: "01570eca-8bd8-4357-985c-c537600bde6e"
  resourceID: "/subscriptions/3ee95fd2-1e28-49f1-a618-84de09c8fcf8/resourceGroups/ebinResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/SopsDecryptorIdentity"
  type: 0 # user-managed identity
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: sops-akv-decryptor-binding
  namespace: flux-system
spec:
  azureIdentity: sops-akv-decryptor
  selector: sops-akv-decryptor  # kustomize-controller label will match this name